name: Node
on:
  push:
    tags:
      - 'node'
jobs:
  node_upload_tool_cache:
    runs-on: ubuntu-24.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Set Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz